SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

GO

CREATE TABLE [dbo].[S2UpdateLog](
	[_id] [int] IDENTITY(1,1) NOT NULL,
	[fixup_id] [int] NULL,
	[id] [int] NULL,
	[old_pathogens] [varchar](400) NULL,
	[new_pathogens] [varchar](400) NULL,
	[old_crops] [varchar](400) NULL,
	[new_crops] [varchar](400) NULL,
	[old_entry_mode] [varchar](100) NULL,
	[new_entry_mode] [varchar](100) NULL,
	[old_chemical] [varchar](100) NULL,
	[new_chemical] [varchar](100) NULL,
 CONSTRAINT [PK_S2UpdateLog] PRIMARY KEY CLUSTERED 
(
	[_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_S2UpdateLog_fixup_id] ON [dbo].[S2UpdateLog]
(
	[fixup_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_S2UpdateLog_s2] ON [dbo].[S2UpdateLog]
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

GO
