SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_get_table_schema] @table NVARCHAR(100)=N'argsTable', @schema NVARCHAR(100) = N'dbo', @db NVARCHAR(100) = NULL
AS
BEGIN
   DECLARE
       @sql    NVARCHAR(4000)
      ,@NL     NVARCHAR(2)       = NCHAR(13) + NCHAR(10)
   DROP TABLE IF EXISTS dbo.table_schema
   CREATE TABLE dbo.table_schema(COLUMN_NAME NVARCHAR(60), DATA_TYPE NVARCHAR(20), CHAR_LEN INT, IS_NULLABLE NVARCHAR(3), ORDINAL INT);
   IF @db IS NULL SET @db = DB_NAME();
   SET @SQL = CONCAT('INSERT INTO dbo.table_schema (COLUMN_NAME, DATA_TYPE, CHAR_LEN, IS_NULLABLE, ORDINAL ) ', @NL
   ,'SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE, ORDINAL_POSITION ', @NL
   ,'FROM ', @db,'.INFORMATION_SCHEMA.COLUMNS ', @NL
   ,'WHERE ',@NL
   ,'   TABLE_SCHEMA   = ''', @schema, ''' AND',@NL
   ,'   TABLE_NAME = ''', @table, ''' ',@NL
   ,'ORDER BY ORDINAL_POSITION;');
   PRINT @SQL;
   EXEC sp_executesql @SQL;
   SELECT * FROM dbo.table_schema;
END
/*
TRUNCATE TABLE dbo.table_schema;
INSERT INTO dbo.table_schema (COLUMN_NAME, DATA_TYPE, CHAR_LEN, IS_NULLABLE, ORDINAL ) 
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE, ORDINAL_POSITION 
FROM Ut.INFORMATION_SCHEMA.COLUMNS 
WHERE 
   TABLE_SCHEMA   = 'dbo' AND
   TABLE_NAME = 'ArgsTable' 
ORDER BY ORDINAL_POSITION;
SELECT * FROM table_schema;
EXEC [dbo].[sp_get_table_schema] 'ArgsTable'
*/
GO

