SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

GO

CREATE TABLE [dbo].[TableDef](
	[table_id] [int] NOT NULL,
	[table_nm] [varchar](50) NOT NULL,
	[table_type] [varchar](50) NULL,
	[sub_type] [varchar](50) NULL,
	[non_null_flds] [varchar](500) NULL,
 CONSTRAINT [PK_TableDef] PRIMARY KEY CLUSTERED 
(
	[table_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
