SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

GO

CREATE TABLE [dbo].[ImportErrors](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[table] [varchar](50) NOT NULL,
	[field] [varchar](50) NOT NULL,
	[msg] [varchar](2000) NOT NULL,
	[cnt] [int] NOT NULL,
 CONSTRAINT [PK_ImportErrors] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
