SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

GO

CREATE TABLE [dbo].[PathogenTypeStaging](
	[pathogenType_id] [int] NULL,
	[pathogenType_nm] [varchar](50) NULL,
 CONSTRAINT [UQ_PathogenTypeStaging] UNIQUE NONCLUSTERED 
(
	[pathogenType_nm] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
