SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

GO

CREATE TABLE [dbo].[ReqUnusedRtns](
	[schema_nm] [varchar](32) NOT NULL,
	[rtn_nm] [varchar](50) NOT NULL,
	[ty_code] [varchar](2) NOT NULL,
	[ordinal] [int] NOT NULL,
	[reason] [varchar](100) NULL,
 CONSTRAINT [IX_ReqUnusedRtns] UNIQUE NONCLUSTERED 
(
	[rtn_nm] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
