SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

GO

CREATE TABLE [dbo].[ChemicalUse](
	[chemical_id] [int] NULL,
	[use_id] [int] NULL,
	[chemical_nm] [varchar](100) NULL,
	[use_nm] [varchar](50) NULL
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_Chemical2Type_chemical] ON [dbo].[ChemicalUse]
(
	[chemical_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_Chemical2Type_type] ON [dbo].[ChemicalUse]
(
	[use_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_ChemicalUse] ON [dbo].[ChemicalUse]
(
	[chemical_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

ALTER TABLE [dbo].[ChemicalUse]  WITH CHECK ADD  CONSTRAINT [FK_ChemicalUse_Chemical] FOREIGN KEY([chemical_id])
REFERENCES [dbo].[Chemical] ([chemical_id])

ALTER TABLE [dbo].[ChemicalUse] CHECK CONSTRAINT [FK_ChemicalUse_Chemical]

ALTER TABLE [dbo].[ChemicalUse]  WITH CHECK ADD  CONSTRAINT [FK_ChemicalUse_Use] FOREIGN KEY([use_id])
REFERENCES [dbo].[Use] ([use_id])

ALTER TABLE [dbo].[ChemicalUse] CHECK CONSTRAINT [FK_ChemicalUse_Use]

GO
