-- DropAndRecreateTestDatabase.SQL
USE MASTER
GO

IF EXISTS 
   (
     SELECT name FROM master.dbo.sysdatabases 
    WHERE name = N'<DB_NAME>'
    )
BEGIN
  ALTER DATABASE [<DB_NAME>] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
	DROP DATABASE [<DB_NAME>]
END
GO

CREATE DATABASE [<DB_NAME>]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'<DB_NAME>', FILENAME = N'<PATH TAG>\<DB_NAME>.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'<DB_NAME>_log', FILENAME = N'<PATH TAG>\<DB_NAME>_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
